#!/usr/bin/env node
/**
 * agent-memory — keeps this repository's shared subagent memory (`.claude/agent-memory/<agent>/`)
 * consistent and reviewable. Protocol: `.claude/skills/agent-memory/SKILL.md`.
 *
 *   node .claude/scripts/agent-memory.mjs index [agent]            Regenerate MEMORY.md from topic-file
 *                                                                   frontmatter (all agents, or one).
 *   node .claude/scripts/agent-memory.mjs check [agent] [--verify] Lint the stores; --verify also runs
 *                                                                   each memory's read-only `verify`
 *                                                                   (parsed and run without a shell).
 *
 * Errors (exit 1) must be fixed before memory changes are committed; warnings need a look. Works from
 * any folder: the repository root is found from this script's location. A "store" is the
 * `.claude/agent-memory/` folder beside a `.claude/agents/` folder. Any other agent-memory folder that
 * holds files is a stray (usually from a session launched in a subdirectory), and
 * `.claude/agent-memory-local/` is never used: shared memory must hold on every machine. `index` never
 * overwrites a MEMORY.md holding hand-written lines (a legacy index or inline facts); `check` reports
 * E_LEGACY_INDEX until those facts live in topic files. No dependencies; Node 18+.
 */

import {spawnSync} from 'node:child_process';
import {existsSync, lstatSync, readdirSync, readFileSync, statSync, writeFileSync} from 'node:fs';
import {hostname} from 'node:os';
import {basename, dirname, join, relative, sep} from 'node:path';
import {fileURLToPath} from 'node:url';

function repoRoot() {
	const here = dirname(fileURLToPath(import.meta.url));
	if (basename(here) === 'scripts' && basename(dirname(here)) === '.claude') return dirname(dirname(here));
	const r = spawnSync('git', ['rev-parse', '--show-toplevel'], {encoding: 'utf8'});
	return r.status === 0 ? r.stdout.trim() : process.cwd();
}

const ROOT = repoRoot();
const PRUNE = new Set(['node_modules', '.git', '.next', 'dist', 'build', '.vercel', 'vendor', 'coverage', 'temp', 'worktrees']);
const TYPES = ['project', 'feedback', 'reference'];
const INDEX_HEADER = '<!-- Generated by `node .claude/scripts/agent-memory.mjs index`. Edit topic files, not this index. -->';
const MAX_INDEX_LINE = 150;
const MAX_ENTRIES = 60;
const MAX_TOPIC_BYTES = 4096;
const STALE_DAYS = 90;

const rel = (p) => relative(ROOT, p).split(sep).join('/');
const lf = (s) => s.replace(/\r\n/g, '\n').replace(/^\uFEFF/, '');
const isFixture = (p) => /\/(test|tests|fixtures|__fixtures__|snapshots)\//.test('/' + rel(p) + '/');
const hasFiles = (dir) => {
	try {
		return readdirSync(dir, {withFileTypes: true}).some((e) => (e.isDirectory() ? hasFiles(join(dir, e.name)) : true));
	} catch {
		return false;
	}
};

/** Every `.claude` folder in the repo (pruned walk). */
function claudeDirs(dir = ROOT, out = []) {
	let entries;
	try {
		entries = readdirSync(dir, {withFileTypes: true});
	} catch {
		return out;
	}
	for (const e of entries) {
		if (!e.isDirectory() || PRUNE.has(e.name)) continue;
		const p = join(dir, e.name);
		if (e.name === '.claude') out.push(p);
		else claudeDirs(p, out);
	}
	return out;
}

function discover() {
	const stores = [];
	const strays = [];
	for (const c of claudeDirs()) {
		if (isFixture(c)) continue;
		const mem = join(c, 'agent-memory');
		const st = lstatSync(mem, {throwIfNoEntry: false});
		if (st && !st.isDirectory()) strays.push(mem); // a link or file is never a store
		else if (st) {
			if (existsSync(join(c, 'agents'))) stores.push(mem);
			// Claude Code creates an empty agent-memory folder on a subdirectory launch; only a stray
			// that holds files matters.
			else if (hasFiles(mem)) strays.push(mem);
		}
		const local = join(c, 'agent-memory-local');
		if (existsSync(local) && hasFiles(local)) strays.push(local);
	}
	return {stores, strays};
}

// Claude Code auto-creates an empty agent folder at spawn; only a folder holding files is a store.
function agentDirs(store, only) {
	return readdirSync(store, {withFileTypes: true})
		.filter((e) => e.isDirectory() && (!only || e.name === only))
		.map((e) => join(store, e.name))
		.filter(hasFiles);
}

/** Minimal frontmatter parser: top-level `key: value`, plus `metadata:` children. */
function parse(text) {
	const t = lf(text);
	const m = /^---\n([\s\S]*?)\n---(?:\n|$)/.exec(t);
	if (!m) return {fm: null, body: t};
	const fm = {};
	let parent = null;
	for (const line of m[1].split('\n')) {
		const kv = /^(\s*)([A-Za-z_][\w-]*):\s*(.*)$/.exec(line);
		if (!kv) continue;
		const [, indent, key, raw] = kv;
		const val = raw.trim().replace(/^(["'])(.*)\1$/, '$2').trim(); // a matched pair of quotes only
		if (!indent && val === '') {
			parent = key;
			fm[key] = fm[key] || {};
		} else if (indent && parent && typeof fm[parent] === 'object') fm[parent][key] = val;
		else {
			parent = null;
			fm[key] = val;
		}
	}
	return {fm, body: t.slice(m[0].length)};
}

// Protocol fields live under `metadata:`; top-level copies (older notes) are accepted.
const field = (fm, key) => (fm && (fm.metadata?.[key] ?? fm[key])) || '';

function topics(agentDir) {
	return readdirSync(agentDir, {withFileTypes: true})
		.filter((e) => e.isFile() && e.name.endsWith('.md') && e.name !== 'MEMORY.md') // symlinks are errors in check
		.map((e) => e.name)
		.sort()
		.map((f) => {
			const path = join(agentDir, f);
			const text = readFileSync(path, 'utf8');
			return {file: f, path, text, bytes: Buffer.byteLength(text), ...parse(text)};
		});
}

function buildIndex(agentDir) {
	const agent = basename(agentDir);
	const items = topics(agentDir);
	const out = [INDEX_HEADER, `# ${agent} memory`, ''];
	const title = (t) => field(t.fm, 'name') || t.file;
	for (const type of TYPES) {
		const group = items.filter((t) => field(t.fm, 'type') === type);
		if (!group.length) continue;
		out.push(`## ${type[0].toUpperCase()}${type.slice(1)}`);
		// Plain code-unit order, so every machine generates the same index.
		for (const t of group.sort((a, b) => (title(a) < title(b) ? -1 : title(a) > title(b) ? 1 : 0))) {
			let line = `- [${title(t)}](${t.file}) — ${field(t.fm, 'description')}`.trimEnd();
			// Cut by code points, so an emoji is never split into a lone surrogate.
			if (line.length > MAX_INDEX_LINE) line = cut(line, MAX_INDEX_LINE - 1) + '…';
			out.push(line);
		}
		out.push('');
	}
	const untyped = items.filter((t) => !TYPES.includes(field(t.fm, 'type')));
	if (untyped.length) {
		out.push('## Needs a valid type (see check)');
		for (const t of untyped) out.push(`- [${t.file}](${t.file})`);
		out.push('');
	}
	return out.join('\n').replace(/\n+$/, '\n');
}

/** The first `max` UTF-16 units of `s`, never ending inside a surrogate pair. */
function cut(s, max) {
	let out = '';
	for (const ch of s) {
		if (out.length + ch.length > max) break;
		out += ch;
	}
	return out;
}

/**
 * Lines of an existing MEMORY.md that `index` would discard. A generated index (first line is
 * INDEX_HEADER) holds only headings and `- [name](file.md)` links; anything else was hand-written. A
 * legacy index (no header) counts whole, because its hooks may carry facts no topic file has.
 */
function handWritten(agentDir) {
	const idx = join(agentDir, 'MEMORY.md');
	if (!lstatSync(idx, {throwIfNoEntry: false})?.isFile()) return [];
	const lines = lf(readFileSync(idx, 'utf8')).split('\n');
	const generated = lines[0] === INDEX_HEADER;
	const link = /^- \[[^\]]*\]\([^)\s]+\.md\)/;
	return lines.filter((l) => l.trim() && l !== INDEX_HEADER && !/^#{1,6}\s/.test(l) && !(generated && link.test(l)));
}

// ---------------------------------------------------------------- check rules

const ABS_PATH = /(?:^|[\s`'"(=])(?:[A-Za-z]:[\\/](?!\/)|\/[a-z]\/Users\/|\/home\/[a-z]|\/Users\/[A-Za-z]|~\/)/;
const SECRETS = [
	/\bAKIA[0-9A-Z]{16}\b/,
	/-----BEGIN [A-Z ]*PRIVATE KEY-----/,
	/\bgh[pousr]_[A-Za-z0-9]{36,}\b/,
	/\bgithub_pat_[A-Za-z0-9_]{40,}/,
	/\bsk-(?=[A-Za-z0-9_-]*[A-Z])(?=[A-Za-z0-9_-]*[a-z])(?=[A-Za-z0-9_-]*\d)[A-Za-z0-9_-]{32,}/,
	/\b[rs]k_live_[A-Za-z0-9]{16,}/,
	/\bxox[abprs]-[A-Za-z0-9-]{10,}/,
	/hooks\.slack\.com\/services\/[A-Z0-9]+\/[A-Z0-9]+\/[A-Za-z0-9]+/,
	/\bAIza[0-9A-Za-z_-]{35}\b/,
	/\beyJ[A-Za-z0-9_-]{10,}\.eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}/,
	/\b[a-z][a-z0-9+.-]*:\/\/[^\s:@/`'"]+:[^\s@/`'"]+@/i // credentials inside a URL
];
// "creds `user`/`pass`": flagged unless both values are env-var names or placeholders.
const CRED_PAIR = /\bcred(?:s|entials?)?\b[^\n`]{0,30}`([^`\s]{3,})`\s*\/\s*`([^`\s]{4,})`/gi;
// "the … password `Xy12!…`": a backticked literal right after the word (not a path or code).
const PASSWORD_LITERAL = /\b(?:password|passwd|pwd|passphrase)\b(?::|\s(?:is|was|=))?\s{0,2}`([^`\s]{6,})`/gi;
const LOOKS_LIKE_CODE = /^[/[.-]|[/().:=]/;
// Bare "token" is left out on purpose: in these notes it mostly names non-secret IDs (checkout tokens).
const CRED_WORD = String.raw`password|passwd|pwd|passphrase|x-api-key|api[\s_-]?key|secret|client[_-]?secret|(?:access|auth|api|bearer)[\s_-]?token|bearer`;
// key = value (or "key is value"), where the value looks like a literal secret.
const CREDENTIAL = new RegExp(String.raw`\b(?:${CRED_WORD})\b["'\x60]?\s*(?:[:=]|\s(?:is|was)\s)\s*["'\x60]?([A-Za-z0-9][^\s"'\x60,;)]{7,})`, 'gi');
// A quoted literal shortly after a credential word: "the Tools-API key is `…`", "x-api-key header `…`".
const CRED_NEAR = new RegExp(String.raw`\b(?:${CRED_WORD})\b[^\n\x60"']{0,40}[\x60"']([^\x60"'\s]{8,})[\x60"']`, 'gi');
// Env-var names (with an underscore), plain words, placeholders, paths, URLs and ARNs are not secrets.
const NOT_A_SECRET = /^(?:[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)+|[A-Z]+|\$\{.*|process\.env.*|<.*>|\*+|x+|.*\/secrets?\/.*|arn:aws:secretsmanager:.*|https?:\/\/.*|[a-z]+(?:[-_][a-z]+)*|[A-Z][a-z]+)$/;
// A literal worth flagging: 8+ chars, not code-shaped, and letters with digits, or (no digits) mixed case
// dense enough not to be an identifier such as accessToken or PropertiesService.
const looksSecret = (v) => {
	if (v.length < 8 || NOT_A_SECRET.test(v) || LOOKS_LIKE_CODE.test(v)) return false;
	if (/…|[[\]{}\\]/.test(v)) return false; // truncated (redacted) value, or a regex
	if (/^(?:[A-Z]+|[A-Z]?[a-z]+)(?:[-_](?:[A-Z]+|[A-Z]?[a-z]+))+$/.test(v)) return false; // HMAC-signed, SERVICE_ROLE-key
	const letters = v.replace(/[^A-Za-z]/g, '');
	if (/\d/.test(v)) return letters.length > 0;
	const upper = letters.replace(/[^A-Z]/g, '').length;
	return upper > 0 && upper < letters.length && upper / letters.length >= 0.4;
};
const RELATIVE_DATE = /\b(yesterday|tomorrow|today|last (?:week|month|night)|next (?:week|month)|this (?:week|month|morning|afternoon))\b/i;
const LINE_ANCHOR = /\b[\w./-]+\.(?:m?js|cjs|jsx|tsx?|sql|py|gs|php|json|ya?ml|css|html?):\d+|\bline \d+\b|#L\d+\b/i;
const HOST = hostname();
const LOCAL_ENV = new RegExp(
	String.raw`\blocalhost:\d+|\b127\.0\.0\.1\b|\b192\.168\.\d+\.\d+|\b10\.\d+\.\d+\.\d+|\b172\.(?:1[6-9]|2\d|3[01])\.\d+\.\d+|\bDESKTOP-[A-Z0-9]+\b|\b(?:this|my|[A-Z][a-z]+'?s) (?:PC|machine|laptop|computer)\b` +
		(HOST && HOST.length > 3 ? `|\\b${HOST.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b` : ''),
	'i'
);
const STATUS = /\bNOT (?:yet )?(?:fixed|deployed|pushed|merged)\b|\bin progress\b|\bpending\b|\bTODO\b|\bas of this writing\b/i;
// verify is one read-only command, split into words without a shell and run without one: `test -e|-f
// <repo path>`, or git grep/ls-files/log/show with only these options. git accepts any unambiguous
// prefix of a long option (`--open` means --open-files-in-pager, which runs a program), so options are
// matched exactly against this list and everything else is rejected. `flags` are short flags that may be
// clustered (-nF); a `value` flag takes the rest of its cluster or the next word; `long` take no value;
// `longValue` take `=value` only; `number` allows -<n>.
const GIT_VERIFY = {
	grep: {
		flags: 'nilLwFEGPqcIhHv',
		value: 'e',
		long: ['--line-number', '--ignore-case', '--files-with-matches', '--files-without-match', '--word-regexp', '--fixed-strings', '--extended-regexp', '--basic-regexp', '--perl-regexp', '--quiet', '--count', '--invert-match', '--cached', '--untracked', '--all-match', '--and', '--or', '--not'],
		longValue: []
	},
	'ls-files': {flags: 'cs', value: '', long: ['--error-unmatch', '--cached', '--stage'], longValue: []},
	log: {
		flags: 'iF',
		value: 'nSG',
		number: true,
		long: ['--oneline', '--all', '--follow', '--name-only', '--name-status', '--stat', '--no-merges', '--first-parent', '--regexp-ignore-case', '--fixed-strings', '--pickaxe-regex', '--reverse'],
		longValue: ['--format', '--pretty', '--grep', '--author', '--since', '--until', '--after', '--before', '--diff-filter', '--max-count']
	},
	show: {flags: 's', value: '', long: ['--stat', '--name-only', '--name-status', '--oneline', '--no-patch', '--quiet'], longValue: ['--format', '--pretty']}
};
const SHELL_CHARS = /[;&|<>`$\r\n]/;

/** Split a verify string into words: whitespace separates, '…' and "…" quote (\" and \\ inside "…"). */
function words(cmd) {
	const out = [];
	let cur = null;
	let q = null;
	for (let i = 0; i < cmd.length; i++) {
		const c = cmd[i];
		if (q) {
			if (c === q) q = null;
			else if (c === '\\' && q === '"' && (cmd[i + 1] === '"' || cmd[i + 1] === '\\')) cur += cmd[++i];
			else cur += c;
		} else if (c === '"' || c === "'") {
			q = c;
			cur = cur ?? '';
		} else if (/\s/.test(c)) {
			if (cur !== null) out.push(cur);
			cur = null;
		} else if (c === '\\') return null;
		else cur = (cur ?? '') + c;
	}
	if (q) return null;
	if (cur !== null) out.push(cur);
	return out;
}

const repoPath = (p) => p && !/^(?:[A-Za-z]:|[\\/~-])/.test(p) && !p.split(/[\\/]/).includes('..');

/** The verify command as an argument list, or null when it is not an allowed read-only command. */
function parseVerify(cmd) {
	if (SHELL_CHARS.test(cmd)) return null;
	const a = words(cmd.trim());
	if (!a || !a.length) return null;
	if (a[0] === 'test') return a.length === 3 && (a[1] === '-e' || a[1] === '-f') && repoPath(a[2]) ? a : null;
	const spec = a[0] === 'git' && Object.hasOwn(GIT_VERIFY, a[1]) ? GIT_VERIFY[a[1]] : null;
	if (!spec) return null;
	for (let i = 2; i < a.length; i++) {
		const t = a[i];
		if (t === '--') break;
		if (!t.startsWith('-') || t === '-') continue;
		if (t.startsWith('--')) {
			const eq = t.indexOf('=');
			const name = eq < 0 ? t : t.slice(0, eq);
			if (eq < 0 && spec.long.includes(name)) continue;
			// `--format=…` only: git reads a bare --pretty/--format's next word as its own option.
			if (spec.longValue.includes(name) && eq > 0) continue;
			return null;
		}
		if (spec.number && /^-\d+$/.test(t)) continue;
		for (let j = 1; j < t.length; j++) {
			if (spec.value.includes(t[j])) {
				if (j === t.length - 1 && ++i >= a.length) return null; // -e with no pattern
				break;
			}
			if (!spec.flags.includes(t[j])) return null;
		}
	}
	return a;
}
// These exit 0 even when the fact is false, so they can't reveal staleness.
const WEAK_VERIFY = /^git (?:log\b|ls-files\b(?!.*--error-unmatch))/;
const MANUAL_VERIFY = /^manual\s*[—-]\s*\S/i;
const FILE_NAME = /^(project|feedback|reference)_[a-z0-9]+(?:[-_][a-z0-9]+)*\.md$/;

const prose = (s) => s.replace(/```[\s\S]*?```/g, ' ').replace(/`[^`\n]*`/g, ' ').replace(/"[^"\n]{0,120}"/g, ' ');

function hasSecret(text) {
	if (SECRETS.some((rx) => rx.test(text))) return true;
	for (const m of text.matchAll(CRED_PAIR)) if (!NOT_A_SECRET.test(m[1]) || !NOT_A_SECRET.test(m[2])) return true;
	for (const m of text.matchAll(PASSWORD_LITERAL))
		if (!NOT_A_SECRET.test(m[1]) && !LOOKS_LIKE_CODE.test(m[1]) && /[\d\W_]/.test(m[1])) return true;
	for (const rx of [CREDENTIAL, CRED_NEAR]) for (const m of text.matchAll(rx)) if (looksSecret(m[1])) return true;
	return false;
}

function ignored(path) {
	const r = spawnSync('git', ['check-ignore', '-q', '--no-index', rel(path)], {cwd: ROOT});
	return r.status === 0;
}

/** Run a parsed verify from the repo root: `test` natively, git directly (no shell, no pager). */
function runVerify(a) {
	if (a[0] === 'test') {
		const p = join(ROOT, a[2]);
		return existsSync(p) && (a[1] === '-e' || statSync(p).isFile()) ? 'pass' : 'fail';
	}
	const env = {...process.env, GIT_PAGER: 'cat', PAGER: 'cat'};
	delete env.GIT_EXTERNAL_DIFF;
	const r = spawnSync('git', a.slice(1), {cwd: ROOT, encoding: 'utf8', timeout: 15000, env, shell: false});
	if (r.error) return 'skipped';
	return r.status === 0 ? 'pass' : 'fail';
}

function checkTopic(t, errors, warnings, opts) {
	const at = rel(t.path);
	const E = (code, msg) => errors.push(`${at}: ${code} ${msg}`);
	const W = (code, msg) => warnings.push(`${at}: ${code} ${msg}`);
	if (!t.fm) return E('E_FRONTMATTER', 'no YAML frontmatter');
	const type = field(t.fm, 'type');
	if (type === 'user') E('E_TYPE', "type user is personal: it belongs in the user's own auto memory, not the shared store");
	else if (!TYPES.includes(type)) E('E_TYPE', `type must be one of ${TYPES.join(', ')} (got "${type}")`);
	for (const k of ['name', 'description', 'verified', 'source']) if (!field(t.fm, k)) E('E_FIELD', `missing ${k}`);
	const verify = field(t.fm, 'verify');
	if (type !== 'reference' && !verify) E('E_FIELD', 'missing verify');
	const verified = field(t.fm, 'verified');
	if (verified && !/^\d{4}-\d{2}-\d{2}$/.test(verified)) E('E_FIELD', 'verified must be YYYY-MM-DD');
	if (!FILE_NAME.test(t.file)) E('E_NAME', 'file name must be <type>_<lowercase slug>.md');
	else if (type && TYPES.includes(type) && !t.file.startsWith(`${type}_`)) E('E_NAME', `file name prefix doesn't match type ${type}`);
	if (ABS_PATH.test(t.text)) E('E_ABS_PATH', 'absolute or user-home path; use repo-relative paths');
	if (hasSecret(t.text)) E('E_SECRET', 'looks like a secret or credential; remove it and rotate it');
	if (verify) {
		const argv = MANUAL_VERIFY.test(verify) ? null : parseVerify(verify);
		if (MANUAL_VERIFY.test(verify)) W('W_VERIFY_MANUAL', 'manual verify; fine for database or cross-repo facts, re-check by hand when used');
		else if (!argv)
			E('E_VERIFY', 'verify must be one read-only git grep/ls-files/log/show (only the options SKILL.md §5 lists) or test -e/-f <repo path> command, or "manual — <check>"; never run it by hand');
		else if (WEAK_VERIFY.test(verify)) W('W_VERIFY_WEAK', 'exits 0 even when the fact is false; use git grep (-L for absence), test -e/-f or git ls-files --error-unmatch');
		if (argv && opts.verify) {
			const r = runVerify(argv);
			if (r === 'fail') W('W_VERIFY_FAIL', `verify failed: ${verify} — re-check the fact; fix or delete the note if it is false`);
			if (r === 'skipped') W('W_VERIFY_SKIPPED', 'could not run verify (git not found)');
		}
	}
	const rd = RELATIVE_DATE.exec(prose(t.text));
	if (rd) W('W_REL_DATE', `relative date "${rd[1]}"; write YYYY-MM-DD unless it is domain wording (e.g. "today-only route")`);
	if (LINE_ANCHOR.test(t.text)) W('W_LINE_ANCHOR', 'line-number anchor; anchor on a symbol or key instead');
	if (LOCAL_ENV.test(t.text)) W('W_LOCAL_ENV', 'localhost, private IP, host or "this machine" wording; keep only if it holds on every machine');
	if (STATUS.test(prose(t.body))) W('W_STATUS', 'reads like task status; status belongs in the issue');
	if (t.bytes > MAX_TOPIC_BYTES) W('W_SIZE', `${t.bytes} bytes; one fact per file, under ${MAX_TOPIC_BYTES}`);
	if (/^\d{4}-\d{2}-\d{2}$/.test(verified)) {
		const age = (Date.now() - Date.parse(verified)) / 86400000;
		if (age > STALE_DAYS) W('W_STALE', `verified ${Math.round(age)} days ago; re-confirm the fact itself (not just its verify) and update verified`);
	}
	if (!/^[a-z0-9]+(?:[-_][a-z0-9]+)*$/.test(field(t.fm, 'name'))) W('W_NAME', 'name should be a short kebab-case slug');
	const indexLine = `- [${field(t.fm, 'name') || t.file}](${t.file}) — ${field(t.fm, 'description')}`;
	if (indexLine.length > MAX_INDEX_LINE) W('W_DESC', `index line is ${indexLine.length} chars and gets cut at ${MAX_INDEX_LINE}; shorten the description or the slug`);
}

function check(only, opts) {
	const errors = [];
	const warnings = [];
	const {stores, strays} = discover();
	for (const s of strays)
		errors.push(
			lstatSync(s).isDirectory()
				? `${rel(s)}: E_STRAY not beside a .claude/agents/ folder (or -local scope); merge its notes into the real store and delete it`
				: `${rel(s)}: E_STRAY is a link or file, not a folder; replace it with a real folder`
		);
	for (const store of stores) {
		const agentsDir = join(store, '..', 'agents');
		for (const dir of agentDirs(store, only)) {
			const agent = basename(dir);
			if (!existsSync(join(agentsDir, `${agent}.md`))) warnings.push(`${rel(dir)}: W_ORPHAN no agent definition named ${agent}`);
			for (const e of readdirSync(dir, {withFileTypes: true}))
				if (!e.isFile() || (!e.name.endsWith('.md') && e.name !== '.gitkeep'))
					errors.push(`${rel(join(dir, e.name))}: E_UNEXPECTED_FILE only <type>_<slug>.md topic files and MEMORY.md belong in a store (no folders or links)`);
			const items = topics(dir);
			for (const t of items) checkTopic(t, errors, warnings, opts);
			const names = new Map();
			for (const t of items) {
				const key = field(t.fm, 'name').toLowerCase();
				if (key && names.has(key)) errors.push(`${rel(t.path)}: E_DUPLICATE same name as ${names.get(key)}`);
				else if (key) names.set(key, t.file);
			}
			if (items.length > MAX_ENTRIES) warnings.push(`${rel(dir)}: W_SIZE ${items.length} memories; curate below ${MAX_ENTRIES}`);
			const idx = join(dir, 'MEMORY.md');
			const current = existsSync(idx) ? lf(readFileSync(idx, 'utf8')) : '';
			const hand = handWritten(dir);
			if (hand.length)
				errors.push(
					`${rel(idx)}: E_LEGACY_INDEX ${hand.length} hand-written line(s) that index would discard; move each fact into a topic file or drop it with evidence (curation.md step 3), then delete MEMORY.md and run index`
				);
			else if (current !== buildIndex(dir)) errors.push(`${rel(idx)}: E_INDEX out of date; run \`node .claude/scripts/agent-memory.mjs index ${agent}\``);
			if (ignored(idx)) errors.push(`${rel(dir)}: E_IGNORED_STORE git ignores this store, so it can't be committed; fix .gitignore`);
		}
	}
	return {stores: stores.map(rel), errors, warnings};
}

/** Exit 2 when an agent name was given but no store holds that agent (a typo would otherwise pass). */
function requireAgent(stores, only) {
	// An existing (even emptied) agent folder counts, so a store curated down to nothing still checks.
	if (only && !stores.some((s) => readdirSync(s, {withFileTypes: true}).some((e) => e.isDirectory() && e.name === only))) {
		console.log(`agent-memory: no agent memory named "${only}" (names are case-sensitive)`);
		process.exit(2);
	}
}

// ---------------------------------------------------------------- main

const args = process.argv.slice(2);
const cmd = args[0];
const only = args.slice(1).find((a) => !a.startsWith('--'));
if (cmd === 'index') {
	const {stores} = discover();
	requireAgent(stores, only);
	let n = 0;
	let refused = 0;
	for (const store of stores)
		for (const dir of agentDirs(store, only)) {
			const idx = join(dir, 'MEMORY.md');
			const hand = handWritten(dir);
			const st = lstatSync(idx, {throwIfNoEntry: false}); // lstat: a dangling link still counts
			if (hand.length || (st && !st.isFile())) {
				console.log(`refused ${rel(idx)}: it holds ${hand.length ? `${hand.length} hand-written line(s)` : 'a link, not a file'}; see E_LEGACY_INDEX in check`);
				refused++;
				continue;
			}
			const next = buildIndex(dir);
			// Write only on change, so CRLF checkouts don't show every index as modified.
			if (!st) writeFileSync(idx, next, {flag: 'wx'});
			else {
				const cur = lf(readFileSync(idx, 'utf8'));
				// Say which links lose their line: after a merge one may be an old index's only copy of a fact.
				const linked = cur.split('\n').map((l) => /^- \[[^\]]*\]\(([^)\s]+\.md)\)/.exec(l)?.[1]);
				const gone = [...new Set(linked.filter((f) => f && !existsSync(join(dir, f))))];
				if (gone.length) console.log(`note ${rel(idx)}: dropped the line(s) for ${gone.join(', ')} (no such topic file); if one carried a fact, restore it from git as a topic file`);
				if (cur !== next) writeFileSync(idx, next);
			}
			n++;
		}
	console.log(`indexed ${n} agent memor${n === 1 ? 'y' : 'ies'}${refused ? `, refused ${refused}` : ''}`);
	process.exit(refused ? 1 : 0);
} else if (cmd === 'check') {
	requireAgent(discover().stores, only);
	const r = check(only, {verify: args.includes('--verify')});
	for (const e of r.errors) console.log(`ERROR ${e}`);
	for (const w of r.warnings) console.log(`warn  ${w}`);
	console.log(`agent-memory check: ${r.stores.length} store(s), ${r.errors.length} error(s), ${r.warnings.length} warning(s)`);
	process.exit(r.errors.length ? 1 : 0);
} else {
	console.log('usage: node .claude/scripts/agent-memory.mjs index [agent] | check [agent] [--verify]');
	process.exit(2);
}
